import Link from 'next/link'
import React from 'react'

export function AppFooter() {
  return (
    <footer className="text-center p-2 bg-neutral-100 dark:bg-neutral-900 dark:text-neutral-400 text-xs h-8">
      Generated by{' '}
      <Link className="hover:text-neutral-500 dark:hover:text-white" href="https://github.priyanshpatel.com">
        Priyansh Patel
      </Link>
    </footer>
  )
}
